#____       _   _            _____             _   _      _____
#|  _ \     | | | |          |  __ \           | | | |    / ____|
#| |_) | ___| |_| |_ ___ _ __| |  | | ___  __ _| |_| |__ | (___   ___ _ __ ___  ___ _ __
#|  _ < / _ \ __| __/ _ \ '__| |  | |/ _ \/ _` | __| '_ \ \___ \ / __| '__/ _ \/ _ \ '_ \
#| |_) |  __/ |_| ||  __/ |  | |__| |  __/ (_| | |_| | | |____) | (__| | |  __/  __/ | | |
#|____/ \___|\__|\__\___|_|  |_____/ \___|\__,_|\__|_| |_|_____/ \___|_|  \___|\___|_| |_|

#Author: Tedesk

#The config.yml was created with 1.8.8 in mind.
#Please check the Sounds for your server version!
misc: #Available languages: en-US, pt-BR, zh-TW
  language: 'en-US'
  use-packet-event-handler: true #If this option is disabled, the plugin will change the events of Bukkit instead of events related to packets.
  use-safe-teleport: true
  use-default-world-spawn: true #If this option is enabled, the spawn section on locations.yml will be ignored.
sound:
  type:
    death:
    - BLAZE_DEATH
    - ANVIL_LAND
    - ITEM_PICKUP
    - ENDERMAN_DEATH
    countdown: NOTE_BASS_DRUM
    respawn:
    - NOTE_PLING
    - ORB_PICKUP
    - LEVEL_UP
    kill:
    - SKELETON_DEATH
    - GLASS
  volume:
    death: 1.0
    countdown: 1.0
    respawn: 1.0
    kill: 1.0
  pitch:
    death: 1.0
    countdown: 1.0
    respawn: 1.0
    kill: 1.0
animation: #Available types: NONE, BLOOD, LIGHTNING
  type: "BLOOD"
time:
  duration: 10
permissions:
  instant-respawn: 'bds.respawn'
  keep-xp: 'bds.xp'
  vip-spawn: 'bds.vip'
  admin: 'bds.admin'
spectator-settings:
  queue-teleport: true
  allow-spectate: false
  allow-teleport-with-keys: false
  allow-move: true
  allow-commands: false